@startuml famixFortran
' defineClass
class ProgramFile{
    + filename: String
    + version: String
}

abstract class ProgramUnit{
    + name: String
    + srcSpan: String
    + comment: String
}


abstract class ExternalProcedure{
}

abstract class SubProgram{
}

class Program{
}

class Function{
}

class Subroutine{
}

class BlockData{
}

' defineHierarchy
ProgramFile "1" *-- "1..*" ProgramUnit

ProgramUnit <|-- Program
ProgramUnit <|-- SubProgram
ProgramUnit <|-- ExternalProcedure
ExternalProcedure <|-- Function
ExternalProcedure <|-- Subroutine
SubProgram <|-- BlockData

' defineComment
note right of ProgramFile: A complete <b>program</b> (ProgramFile) consists of <u>one or more program units</u>.\nThere is exactly <u>one main program</u> which begins with a <b>PROGRAM</b> statement\n\n<b>PROGRAM main-name</b>\n\nThis statement appears only at the beginning of the main program and the symbolic\nname main-name must be unique (not used elsewhere in any of the program units).\n\nThere may also be any number of external procedures (<b>functions</b> and <b>subroutines</b>) and <b>BLOCK DATA</b> subprograms.\nEvery program unit must end with an END statement.\n\n<b>END</b>

@enduml