@startuml
hide empty members
skinparam class {
  BackgroundColor white
  ArrowColor black
  BorderColor darkGray
  BackgroundColor<<External>> LightYellow
  BorderColor<<External>> LightGray
}

class ProgramFile << (C,white) >> #FFFFFF {
  String version
  String filename
}
class TWithProgramUnits << (T,lightGrey) >> #FFFFFF {
}
class BlockData << (C,white) >> #FFFFFF {
}
class UnresolvedBehavioral << (C,white) >> #FFFFFF {
}
class SourcedEntity << (C,white) >> #FFFFFF {
}
class Function << (C,white) >> #FFFFFF {
  Boolean isIntrinsic
}
class Entity << (C,white) >> #FFFFFF {
}
class Comment << (C,white) >> #FFFFFF {
  Boolean isEsope
}
class Invocation << (C,white) >> #FFFFFF {
}
class SourceAnchor << (C,white) >> #FFFFFF {
}
class SourceTextAnchor << (C,white) >> #FFFFFF {
}
class ExternalProcedure << (C,white) >> #FFFFFF {
}
class Subroutine << (C,white) >> #FFFFFF {
}
class NamedEntity << (C,white) >> #FFFFFF {
}
class SourceLanguage << (C,white) >> #FFFFFF {
}
class UnknownSourceLanguage << (C,white) >> #FFFFFF {
}
class Parameter << (C,white) >> #FFFFFF {
}
class Variable << (C,white) >> #FFFFFF {
}
class Module << (C,white) >> #FFFFFF {
}
class Program << (C,white) >> #FFFFFF {
}
class FamixFortranModel << (C,white) >> #FFFFFF {
}
class TProgramUnit << (T,lightGrey) >> #FFFFFF {
}
class IndexedFileAnchor << (C,white) >> #FFFFFF {
}

Entity <|-- ProgramFile
TWithProgramUnits <|.. ProgramFile
Entity <|-- BlockData
TProgramUnit <|.. BlockData
ExternalProcedure <|-- UnresolvedBehavioral
Entity <|-- SourcedEntity
ExternalProcedure <|-- Function
SourcedEntity <|-- Comment
Entity <|-- Invocation
Entity <|-- SourceAnchor
SourceAnchor <|-- SourceTextAnchor
Entity <|-- ExternalProcedure
TProgramUnit <|.. ExternalProcedure
ExternalProcedure <|-- Subroutine
Entity <|-- NamedEntity
Entity <|-- SourceLanguage
SourceLanguage <|-- UnknownSourceLanguage
Entity <|-- Parameter
Entity <|-- Variable
Entity <|-- Module
TProgramUnit <|.. Module
Entity <|-- Program
TProgramUnit <|.. Program
TWithProgramUnits <|.. TProgramUnit
SourceAnchor <|-- IndexedFileAnchor

TProgramUnit " *programUnits" --o "container" TWithProgramUnits



@enduml
